"""add enterprise project tables

Revision ID: 4e58a68a462a
Revises: 8abbd3240f1e
Create Date: 2026-01-24 15:31:51.259697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e58a68a462a'
down_revision: Union[str, Sequence[str], None] = '8abbd3240f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise_projects',
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('county_of_origin', sa.String(length=255), nullable=False),
    sa.Column('idea_description', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REJECTED', name='projectstatus'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'grade_level', name='uq_student_grade_project')
    )
    op.create_index(op.f('ix_enterprise_projects_id'), 'enterprise_projects', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_projects_student_id'), 'enterprise_projects', ['student_id'], unique=False)
    op.create_table('enterprise_project_files',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['enterprise_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_project_files_id'), 'enterprise_project_files', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_project_files_project_id'), 'enterprise_project_files', ['project_id'], unique=False)
    op.drop_index(op.f('ix_action_research_phase2_id'), table_name='action_research_phase2')
    op.drop_table('action_research_phase2')
    op.drop_index(op.f('ix_social_enterprise_projects_id'), table_name='social_enterprise_projects')
    op.drop_table('social_enterprise_projects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_action_research_phase3_id'), table_name='action_research_phase3')
    op.drop_table('action_research_phase3')
    op.drop_index(op.f('ix_action_research_phase2_summaries_id'), table_name='action_research_phase2_summaries')
    op.drop_table('action_research_phase2_summaries')
    op.drop_index(op.f('ix_action_research_phase1_id'), table_name='action_research_phase1')
    op.drop_table('action_research_phase1')
    op.drop_index(op.f('ix_action_research_phase1_summaries_id'), table_name='action_research_phase1_summaries')
    op.drop_table('action_research_phase1_summaries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_research_phase1_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phase1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('action_taken', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reflection', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('next_step', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['phase1_id'], ['action_research_phase1.id'], name=op.f('action_research_phase1_summaries_phase1_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('action_research_phase1_summaries_pkey'))
    )
    op.create_index(op.f('ix_action_research_phase1_summaries_id'), 'action_research_phase1_summaries', ['id'], unique=False)
    op.create_table('action_research_phase1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('problem_context', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('problem_statement', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('main_question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('specific_question_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specific_question_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specific_question_3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('literature_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolution_other_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('planned_action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proposed_duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='phasestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('action_research_phase1_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('action_research_phase1_pkey'))
    )
    op.create_index(op.f('ix_action_research_phase1_id'), 'action_research_phase1', ['id'], unique=False)
    op.create_table('action_research_phase2_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phase2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('action_taken', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reflection', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('next_step', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['phase2_id'], ['action_research_phase2.id'], name=op.f('action_research_phase2_summaries_phase2_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('action_research_phase2_summaries_pkey'))
    )
    op.create_index(op.f('ix_action_research_phase2_summaries_id'), 'action_research_phase2_summaries', ['id'], unique=False)
    op.create_table('action_research_phase3',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phase2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('final_reflection', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('comparison_with_other_research', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('situation_change', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('how_would_do_differently', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('impact_of_project', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uploads', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['phase2_id'], ['action_research_phase2.id'], name=op.f('action_research_phase3_phase2_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('action_research_phase3_pkey')),
    sa.UniqueConstraint('phase2_id', name=op.f('action_research_phase3_phase2_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_action_research_phase3_id'), 'action_research_phase3', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_type', postgresql.ENUM('STUDENT', 'TEACHER', name='usertype'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('institution', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tsc_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('national_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('national_id', name=op.f('users_national_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('student_id', name=op.f('users_student_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('tsc_number', name=op.f('users_tsc_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('social_enterprise_projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('county', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('grade_level', postgresql.ENUM('GRADE_10', 'GRADE_11', 'GRADE_12', name='gradelevel'), autoincrement=False, nullable=False),
    sa.Column('idea_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('document_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='projectstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('social_enterprise_projects_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('social_enterprise_projects_pkey'))
    )
    op.create_index(op.f('ix_social_enterprise_projects_id'), 'social_enterprise_projects', ['id'], unique=False)
    op.create_table('action_research_phase2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phase1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_taken', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('observed_outcomes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('evidence_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('reflection', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='phase2status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['phase1_id'], ['action_research_phase1.id'], name=op.f('action_research_phase2_phase1_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('action_research_phase2_pkey'))
    )
    op.create_index(op.f('ix_action_research_phase2_id'), 'action_research_phase2', ['id'], unique=False)
    op.drop_index(op.f('ix_enterprise_project_files_project_id'), table_name='enterprise_project_files')
    op.drop_index(op.f('ix_enterprise_project_files_id'), table_name='enterprise_project_files')
    op.drop_table('enterprise_project_files')
    op.drop_index(op.f('ix_enterprise_projects_student_id'), table_name='enterprise_projects')
    op.drop_index(op.f('ix_enterprise_projects_id'), table_name='enterprise_projects')
    op.drop_table('enterprise_projects')
    # ### end Alembic commands ###
